runtime: nodejs20

instance_class: F2

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|json|svg|txt|html|map|woff|woff2|ttf|eot|otf))
    static_files: build/\1
    upload: build/(.*\.(js|css|png|jpg|jpeg|gif|ico|json|svg|txt|html|map|woff|woff2|ttf|eot|otf))

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
